// SPDX-License-Identifier: Apache-2.0
//
// AUTO-GENERATED by scripts/generate-version.mjs from package.json.
// DO NOT EDIT BY HAND. The build script regenerates this file.
// A unit test in test/version.test.ts asserts VERSION === package.json#version.

export const VERSION = "0.2.0";
export const USER_AGENT = "ari-mcp/0.2.0";
