#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
//
// Auto-generate src/version.ts from package.json so the CLI's --version
// output and the HTTP User-Agent string can never drift from the
// published tarball version again (regression gate for task #545).
// Runs as the first step of `pnpm run build`. The generated file IS
// committed (so editable / un-built test runs still resolve VERSION),
// but every build overwrites it from package.json.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkgPath = join(here, "..", "package.json");
const outPath = join(here, "..", "src", "version.ts");

const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
const version = pkg.version;
if (typeof version !== "string" || !version) {
  throw new Error(`package.json missing version field at ${pkgPath}`);
}

const body =
  "// SPDX-License-Identifier: Apache-2.0\n" +
  "//\n" +
  "// AUTO-GENERATED by scripts/generate-version.mjs from package.json.\n" +
  "// DO NOT EDIT BY HAND. The build script regenerates this file.\n" +
  "// A unit test in test/version.test.ts asserts VERSION === package.json#version.\n" +
  "\n" +
  `export const VERSION = ${JSON.stringify(version)};\n` +
  `export const USER_AGENT = ${JSON.stringify(`ari-mcp/${version}`)};\n`;

writeFileSync(outPath, body);
console.log(`generated ${outPath} → VERSION=${version}`);
